apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nimbuschain

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb-service.yaml
  - mongodb-statefulset.yaml
  - downloads-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - api-hpa.yaml
  - worker-hpa.yaml

images:
  - name: ghcr.io/nimbuschain/nimbus-api
    newTag: latest
  - name: ghcr.io/nimbuschain/nimbus-ui
    newTag: latest
