apiVersion: v1
kind: Service
metadata:
  name: nimbus-mongodb
  namespace: nimbuschain
  labels:
    app: nimbus-mongodb
spec:
  selector:
    app: nimbus-mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
