apiVersion: v1
kind: Secret
metadata:
  name: nimbus-secrets
  namespace: nimbuschain
type: Opaque
stringData:
  NIMBUS_API_KEY: ""
  NIMBUS_COPERNICUS_USERNAME: ""
  NIMBUS_COPERNICUS_PASSWORD: ""
  NIMBUS_USGS_USERNAME: ""
  NIMBUS_USGS_TOKEN: ""
