apiVersion: v1
kind: Service
metadata:
  name: nimbus-ui
  namespace: nimbuschain
  labels:
    app: nimbus-ui
spec:
  selector:
    app: nimbus-ui
  ports:
    - name: http
      port: 8501
      targetPort: http
