apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../k8s
  - pv-mongodb.yaml
  - pv-downloads.yaml

patchesStrategicMerge:
  - patch-downloads-pvc.yaml
  - patch-mongodb-statefulset.yaml
  - patch-api-deployment.yaml
  - patch-worker-deployment.yaml
  - patch-api-hpa.yaml
  - patch-worker-hpa.yaml
